Repository hugovk/pypistats, pull requests merged in 2020-10, with the labels that each got.

#172 Declare support for Python 3.9
  setup.py
Labels: changelog: Added, hacktoberfest-accepted

#180 Fix overall total and percent for "overall"
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  src/pypistats/__init__.py
  tests/test_pypistats.py
Labels: bug, changelog: Fixed

#186 Replace 3.9-dev with 3.9 in .travis.yml to use Python 3.9 final
  .travis.yml
Labels: changelog: Changed, testing
