Repository hugovk/pypistats, pull requests merged in 2023-07, with the labels that each got.

#400 Remove unused 'rich' format
  README.md
  src/pypistats/cli.py
Labels: changelog: Fixed

#403 Remove default 'cache-dependency-path: pyproject.toml'
  .github/workflows/test.yml
Labels: changelog: skip

#402 Add validators for 'python_major' and 'python_minor' arguments
  src/pypistats/cli.py
  tests/test_cli.py
Labels: changelog: Added
