Repository hugovk/pypistats, pull requests merged in 2024-05, with the labels that each got.

#435 Add support for Python 3.13
  .github/workflows/test.yml
  pyproject.toml
  tox.ini
Labels: changelog: Added

#436 Update config
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: changelog: skip

#438 Fix index out of range error when data not found
  src/pypistats/__init__.py
  tests/test_pypistats.py
Labels: changelog: Fixed
