Repository hugovk/pypistats, pull requests merged in 2025-02, with the labels that each got.

#474 Remove GitHub attestation and update config/linting/spelling
  .coveragerc
  .github/renovate.json
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/require-pr-label.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .yamlfmt.yaml
  README.md
  RELEASING.md
  example/example.py
  pyproject.toml
  src/pypistats/cli.py
  tox.ini
Labels: changelog: Changed

#473 Replace deprecated classifier with licence expression (PEP 639)
  pyproject.toml
Labels: changelog: Changed

#471 Updated docs for recent command.
  README.md
  src/pypistats/__init__.py
Labels: changelog: Fixed

#472 README: Update for more concise output with 3.13
  README.md
Labels: changelog: skip
